version: "3"

services:
  web-app:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - worker
      - flower

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/app
    links:
      - redis:redis
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower --address=0.0.0.0 --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
      - db
